"""VPN data

Revision ID: 00f04cfaa303
Revises: 8d3ef4f4c6e7
Create Date: 2024-10-25 15:17:22.716437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f04cfaa303'
down_revision = '8d3ef4f4c6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vpn_username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vpn_password', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vpn_ip', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vpn_preshared_key', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_column('vpn_preshared_key')
        batch_op.drop_column('vpn_ip')
        batch_op.drop_column('vpn_password')
        batch_op.drop_column('vpn_username')

    # ### end Alembic commands ###
