"""Int to float

Revision ID: 27a7da13e850
Revises: 2447582877bb
Create Date: 2024-07-30 20:12:28.284012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a7da13e850'
down_revision = '2447582877bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ganancia_por_pagina', schema=None) as batch_op:
        batch_op.alter_column('tokens',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ganancia_por_pagina', schema=None) as batch_op:
        batch_op.alter_column('tokens',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
