"""Añadir modelo SupuestoGanancia

Revision ID: 2b580df74f92
Revises: 
Create Date: 2024-07-24 13:32:22.669985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b580df74f92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supuesto_ganancia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('pagina_id', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Float(), nullable=False),
    sa.Column('total_cop', sa.Float(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('inicio_periodo', sa.Date(), nullable=False),
    sa.Column('fin_periodo', sa.Date(), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo.id'], ),
    sa.ForeignKeyConstraint(['pagina_id'], ['pagina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jornada', sa.String(length=50), nullable=True))
        batch_op.alter_column('tipo_documento',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('numero_documento',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('banco',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('numero_cuenta',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('habilitado',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('exclusividad',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['correo_electronico'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('exclusividad',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('habilitado',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('numero_cuenta',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('banco',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('numero_documento',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('tipo_documento',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('jornada')

    op.drop_table('supuesto_ganancia')
    # ### end Alembic commands ###
