"""time worked

Revision ID: 9875c93ed9c4
Revises: 5edd2587eb5e
Create Date: 2025-01-23 18:53:45.963461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9875c93ed9c4'
down_revision = '5edd2587eb5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earnings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours_worked', sa.Interval(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earnings', schema=None) as batch_op:
        batch_op.drop_column('hours_worked')

    # ### end Alembic commands ###
