"""eargnings scrapper table

Revision ID: db958c0092d6
Revises: 6b3e19a9a317
Create Date: 2024-12-27 19:21:02.636559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db958c0092d6'
down_revision = '6b3e19a9a317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('dollars', sa.Float(), nullable=False),
    sa.Column('tokens', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('page_name', sa.String(length=50), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earnings')
    # ### end Alembic commands ###
