"""eargnings users

Revision ID: f8b6dece75ca
Revises: c0e06cb55159
Create Date: 2024-12-28 03:48:01.699211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b6dece75ca'
down_revision = 'c0e06cb55159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earnings_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earnings_users', schema=None) as batch_op:
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
