"""Añadir modelo SupuestoGananciaaaaaa

Revision ID: 2447582877bb
Revises: 2b580df74f92
Create Date: 2024-07-24 14:03:35.207912

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2447582877bb"
down_revision = "2b580df74f92"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("modelo", schema=None) as batch_op:
        batch_op.add_column(sa.Column("password", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("modelo", schema=None) as batch_op:
        batch_op.drop_column("password")

    # ### end Alembic commands ###
