"""Agregar campo precio al modelo Inventario 2

Revision ID: 2fb39845dd7c
Revises: f6290bd062bf
Create Date: 2025-01-26 10:20:04.376137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb39845dd7c'
down_revision = 'f6290bd062bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.drop_column('precio')

    # ### end Alembic commands ###
