"""Agregar campo creado_por a Deducible

Revision ID: 4a72fe21a064
Revises: f83c02d7c7ab
Create Date: 2025-01-28 10:04:29.501671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a72fe21a064'
down_revision = 'f83c02d7c7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deducible', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_por', sa.String(length=50), nullable=True))

    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.alter_column('categoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.alter_column('categoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('deducible', schema=None) as batch_op:
        batch_op.drop_column('creado_por')

    # ### end Alembic commands ###
