"""Agregar campo estado item

Revision ID: 531d8ef77b75
Revises: 6e6769974b01
Create Date: 2025-01-26 15:28:24.655732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531d8ef77b75'
down_revision = '6e6769974b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_articulo', sa.String(length=50), nullable=True))
        batch_op.drop_column('estado_item')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_item', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('estado_articulo')

    # ### end Alembic commands ###
