"""modify earnings user table

Revision ID: 5edd2587eb5e
Revises: f8b6dece75ca
Create Date: 2025-01-08 20:58:01.673505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5edd2587eb5e'
down_revision = 'f8b6dece75ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earnings_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jornada', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_satelite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earnings_users', schema=None) as batch_op:
        batch_op.drop_column('is_satelite')
        batch_op.drop_column('jornada')

    # ### end Alembic commands ###
