"""Agregar campo estado item

Revision ID: 6e6769974b01
Revises: 2fb39845dd7c
Create Date: 2025-01-26 15:13:14.220211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6769974b01'
down_revision = '2fb39845dd7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_item', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.drop_column('estado_item')

    # ### end Alembic commands ###
