"""Agregar el campo porcentaje base

Revision ID: 8575c3328b35
Revises: d99a3536c28c
Create Date: 2024-11-12 13:33:35.764262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8575c3328b35'
down_revision = 'd99a3536c28c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('porcentaje_base', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_column('porcentaje_base')

    # ### end Alembic commands ###
