"""Agregar campo meta mensual

Revision ID: 8caf48db4700
Revises: 4a72fe21a064
Create Date: 2025-02-12 17:02:21.813800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8caf48db4700'
down_revision = '4a72fe21a064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periodo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_periodo', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periodo', schema=None) as batch_op:
        batch_op.drop_column('meta_periodo')

    # ### end Alembic commands ###
