"""Agregar campo usuario_modificacion a inventario

Revision ID: bbfc4928fb7e
Revises: 9875c93ed9c4
Create Date: 2025-01-25 19:36:05.437938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbfc4928fb7e'
down_revision = '9875c93ed9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_satelite', sa.Boolean(), nullable=True))
        batch_op.drop_column('vpn_password')
        batch_op.drop_column('vpn_username')
        batch_op.drop_column('vpn_preshared_key')
        batch_op.drop_column('vpn_ip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vpn_ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vpn_preshared_key', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vpn_username', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vpn_password', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('es_satelite')

    # ### end Alembic commands ###
