"""Agregar el campo Celular al modelo de usuario

Revision ID: d99a3536c28c
Revises: 00f04cfaa303
Create Date: 2024-11-12 10:44:25.676748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99a3536c28c'
down_revision = '00f04cfaa303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_celular', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_column('numero_celular')

    # ### end Alembic commands ###
