name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy using SSH with password
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no dahouse@vnc.dahouse.co << 'EOF'
          cd /var/www/dahouse-full
          git fetch --all
          git reset --hard origin/main
          yarn install --cwd ./frontend
          yarn build --cwd ./frontend
          pm2 reload ecosystem.config.cjs --env production
        EOF
