name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # or whatever version you're using

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy using SSH with password
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no dahouse@vnc.dahouse.co << 'EOF'
          cd /var/www/dahouse-full
          git fetch --all
          git reset --hard origin/main
          cd frontend
          yarn install
          yarn build  # Changed from yarn build to yarn nuxt build
          cd ..
          pm2 delete NuxtFrontend
          pm2 delete Backend
          pm2 start ecosystem.config.cjs
          pm2 save
          pm2 list
        EOF